# Generated by Django 5.0.6 on 2024-07-13 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('desc', models.CharField(max_length=255, null=True)),
                ('credit', models.IntegerField(default=1)),
                ('debit', models.IntegerField(default=-1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('cur_bal', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('acc_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('acc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.acctype')),
            ],
        ),
    ]
