# Generated by Django 5.0.6 on 2024-07-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_account_credit_alter_account_cur_bal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='credit',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='debit',
            field=models.IntegerField(blank=True),
        ),
    ]
