# Generated by Django 5.0.6 on 2024-07-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_account_credit_alter_account_debit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='account',
            name='debit',
        ),
        migrations.AddField(
            model_name='account',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Credit'), (-1, 'Debit')], default=1),
            preserve_default=False,
        ),
    ]
