# Generated by Django 5.0.6 on 2024-07-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_transaction_codes_transaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cur_bal',
        ),
    ]
