# Generated by Django 5.0.6 on 2024-07-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_ccctype_transaction_acctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction_codes',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Credit'), (-1, 'Debit')]),
        ),
    ]
