# Generated by Django 5.0.6 on 2024-07-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_account_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_bonus',
            name='bonus',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
