# Generated by Django 5.0.6 on 2024-07-13 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_product_bonus_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='package',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.products'),
        ),
    ]
