# Generated by Django 5.0.6 on 2024-07-13 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_orders_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.products'),
        ),
    ]
