# Generated by Django 5.0.6 on 2024-07-14 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_orders_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus_tran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trandate', models.DateTimeField(auto_now_add=True)),
                ('rundate', models.DateTimeField()),
                ('status', models.CharField(choices=[('Processed', 'Processed'), ('Pending', 'Pending')], default='Pending', max_length=255)),
                ('acc_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.acctype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.orders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
