# Generated by Django 5.0.6 on 2024-07-14 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_bonus_tran'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus_tran',
            name='tc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.transaction_codes'),
            preserve_default=False,
        ),
    ]
