# Generated by Django 5.0.6 on 2024-07-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_bonus_tran_tc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus_tran',
            name='statust',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
