# Generated by Django 5.0.6 on 2024-07-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_bonus_tran_statust'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus_tran',
            name='statust',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='my_status',
            field=models.CharField(blank=True, choices=[('inactive', 'Instant'), ('renewal', 'Weekly'), ('active', 'Weekend')], max_length=255, null=True),
        ),
    ]
